/** Nomes legíveis das ações conhecidas; as demais aparecem como gravadas. */
export const ACTION_LABELS: Record<string, string> = {
  'auth.login_succeeded': 'Login',
  'auth.login_failed': 'Login recusado',
  'auth.logout': 'Logout',
  'auth.mfa_enabled': 'MFA ativado',
  'auth.mfa_failed': 'Código MFA recusado',
  'auth.refresh_token_reused': 'Reuso de sessão detectado',
  'role.created': 'Perfil criado',
  'role.updated': 'Perfil alterado',
  'role.deleted': 'Perfil excluído',
  'user.roles_changed': 'Perfis do usuário alterados',
  'user.mfa_reset': 'MFA redefinido pelo RH/Admin',
  'sensitive_data.read': 'Leitura de dado sensível',
  'patrol_point.created': 'Ponto de ronda criado',
  'patrol_point.updated': 'Ponto de ronda alterado',
  'patrol_point.deleted': 'Ponto de ronda excluído',
  'patrol_point.code_regenerated': 'Novo QR de ponto de ronda',
  'patrol_route.created': 'Rota de ronda criada',
  'patrol_route.updated': 'Rota de ronda alterada',
  'patrol_route.deleted': 'Rota de ronda excluída',
  'employee.schedule_assigned': 'Escala vinculada',
  'employee.schedule_unassigned': 'Vínculo de escala removido',
};
